site_name: Apuntes LMI y EDD 24/25
theme:
  name: 'material'
  custom_dir: 'overrides'
  palette:
    primary: '#3f51b5'
    accent: '#e91e63'
    background: '#ffffff'
    surface: '#f5f5f5'
    error: '#f44336'
extra_css:
  - './docs/overrides/extra.css'

palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode