site_name: Apuntes LMI y EDD 24/25
theme:
  name: 'material'
  custom_dir: 'overrides'
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - contecnt.tabs.link
    - content.code.annotation
    - contenct.code.copy  
  language: esp
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple      
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

  extra_css:
    - './docs/overrides/extra.css'

      