site_name: Apuntes LMI y EDD 24/25
theme:
  name: 'material'
#  custom_dir: 'overrides'
  palette:
    primary: '#3f51b5'
    accent: '#e91e63'
    background: '#ffffff'
    surface: '#f5f5f5'
    error: '#f44336'
  extra_css:
    - 'overrides/extra.css'

nav:
  - Inicio: index.md
  - Entorno De Desarrollo [EDD]
    - U1. Desenvolupament de software
      - Actividad 01: ./EDD/T1/Documento_01.md
      - Actividad 02: ./EDD/T1/Documento_02.md
      - Actividad 03: ./EDD/T1/Documento_03.md
      - Actividad 04: ./EDD/T1/Documento_04.md
      - Actividad 05: ./EDD/T1/Documento_05.md
      - Actividad 06: ./EDD/T1/Documento_06.md
    - U2. Eines de Desenvolupament. Entorns integrats
    - U3. Sistemes de Control de Versions
    - U4. La plataforma Java. Eines d'automatitzaci贸
  - Lenguaje de Marcas y Sistemas [LMI]
    - U1. Caracteritzaci贸 dels llenguatges de marques
    - U2. Utilitzaci贸 de llenguatges de marques en entorns web: HTML i CSS
    - U3. Manipulaci贸 de documents web: Javascript
