site_name: My Docs
theme:
  name: 'material'
#  custom_dir: 'overrides'
  palette:
    primary: '#3f51b5'
    accent: '#e91e63'
    background: '#ffffff'
    surface: '#f5f5f5'
    error: '#f44336'
extra_css:
  - 'overrides/extra.css'