site_name: Apuntes LMI y EDD 24/25
theme:
  name: 'material'
#  custom_dir: 'overrides'
  palette:
    primary: '#3f51b5'
    accent: '#e91e63'
    background: '#ffffff'
    surface: '#f5f5f5'
    error: '#f44336'
  extra_css:
    - '.docs/overrides/extra.css'

nav:
  - Inicio: './docs/index.md'
  - "Entorno De Desarrollo [EDD]":
    - "U1. Desenvolupament de software":
      - "Actividad 01": 'EDD/T1/Documento_01.md'
      - "Actividad 02": 'EDD/T1/Documento_02.md'
      - "Actividad 03": 'EDD/T1/Documento_03.md'
      - "Actividad 04": 'EDD/T1/Documento_04.md'
      - "Actividad 05": 'EDD/T1/Documento_05.md'
      - "Actividad 06": 'EDD/T1/Documento_06.md'
    - "U2. Eines de Desenvolupament. Entorns integrats":
    - "U3. Sistemes de Control de Versions":
      - "Actividad 01": 'EDD/T3/ej1.md'
      - "Apuntes": 'EDD/T3/ejercicio.md'
    - "U4. La plataforma Java. Eines d'automatitzaci贸":
      - "Actividad 01": 'EDD/T4/Actividad.md'

  - "Lenguaje de Marcas y Sistemas [LMI]":
    - "U1. Caracteritzaci贸 dels llenguatges de marques":
      - "Actividad 01": 'LMI/T1/Documento_01.md'
      - "Actividad 02": 'LMI/T1/Documento_02.md'
    - "U2. Utilitzaci贸 de llenguatges de marques en entorns web HTML i CSS":
      - "Actividades html":
        - "Actividad 01": 'LMI/T2/ej1.html'
        - "Actividad 02": 'LMI/T2/ej2.html'
        - "Actividad 03": 'LMI/T2/ej3.html'
        - "Actividad 04": 'LMI/T2/ej4.html'
        - "Actividad 05": 'LMI/T2/ej5.html'
        - "Actividad 06": 'LMI/T2/ej6.html'
        - "Actividad 07": 'LMI/T2/ej7.html'
        - "Actividad 08": 'LMI/T2/ej8.html'
        - "Actividad 09": 'LMI/T2/ej9.html'
        - "Actividad 10": 'LMI/T2/ej10.html'
        - "Actividad 11": 'LMI/T2/ej11.html'
        - "Actividad 12": 'LMI/T2/ej12.html'
      - "Modificados + css":
    - "U3. Manipulaci贸 de documents web Javascript":
        
