# hola
site_name: Apuntes LMI y EDD 24/25
theme:
  name: material
  font:
    text: Merriwather Sans
    code: Red Hat Mono
  icon:
    logo: fontawesome/solid/r
  # logo: <url img>
  # favicon: <url img>
  features:
    - navigation.footer
#  custom_dir: 'overrides'
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
      # background: '#fffff'
      # surface: '#f5f5f5'
      # error: '#f44336'
    # Light Mode
    - scheme: dafault
      toggle:
        icon: material/weather-night
        name: Dark mode
      primary: blue
      accent: deep orange
  extra_css:
    - '.docs/overrides/extra.css'
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      # emoji_index: !!python/name:material.extensions.emoji.twemoji
      # emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: pymdownx.superfences.fence_code_format
        # format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra: 
  social:
    - icon: simple/github

copyright: Copyright &copy; 2025 Roly Alcoser Rocha

nav:
  - Inicio: './docs/index.md'
  - "Entorno De Desarrollo [EDD]":
    - "U1. Desenvolupament de software":
      - "Actividad 01": 'EDD/T1/Documento_01.md'
      - "Actividad 02": 'EDD/T1/Documento_02.md'
      - "Actividad 03": 'EDD/T1/Documento_03.md'
      - "Actividad 04": 'EDD/T1/Documento_04.md'
      - "Actividad 05": 'EDD/T1/Documento_05.md'
      - "Actividad 06": 'EDD/T1/Documento_06.md'
    - "U2. Eines de Desenvolupament. Entorns integrats": []
    - "U3. Sistemes de Control de Versions":
      - "Actividad 01": 'EDD/T3/ej1.md'
      - "Apuntes": 'EDD/T3/ejercicio.md'
    - "U4. La plataforma Java. Eines d'automatitzaci贸":
      - "Actividad 01": 'EDD/T4/Actividad.md'
      - "Actividad 02": 'EDD/T4/Ant.md'
      - "Actividad 03": 'EDD/T4/Maven.md'

  - "Lenguaje de Marcas y Sistemas [LMI]":
    - "U1. Caracteritzaci贸 dels llenguatges de marques":
      - "Actividad 01": 'LMI/T1/Documento_01.md'
      - "Actividad 02": 'LMI/T1/Documento_02.md'
    - "U2. Utilitzaci贸 de llenguatges de marques en entorns web HTML i CSS":
      - "Actividades html":
        - "Actividad 01": 'LMI/T2/ej1.html'
        - "Actividad 02": 'LMI/T2/ej2.html'
        - "Actividad 03": 'LMI/T2/ej3.html'
        - "Actividad 04": 'LMI/T2/ej4.html'
        - "Actividad 05": 'LMI/T2/ej5.html'
        - "Actividad 06": 'LMI/T2/ej6.html'
        - "Actividad 07": 'LMI/T2/ej7.html'
        - "Actividad 08": 'LMI/T2/ej8.html'
        - "Actividad 09": 'LMI/T2/ej9.html'
        - "Actividad 10": 'LMI/T2/ej10.html'
        - "Actividad 11": 'LMI/T2/ej11.html'
        - "Actividad 12": 'LMI/T2/ej12.html'
      - "Modificados + css":
        - "Actividad 13": 'LMI/T2/modificados/ej11_modif.html'
        - "Actividad 14": 'LMI/T2/modificados/ej12_modif.html'
        - "Actividad 15": 'LMI/T2/modificados/form_registro.html'
    - "U3. Manipulaci贸 de documents web Javascript":
      - "Elementos de lenguaje":
        - "Actividad 01": 'LMI/T3/Elementos-de-lenguaje/ej1.js'
        - "Actividad 02": 'LMI/T3/Elementos-de-lenguaje/ej2.js'
        - "Actividad 03": 'LMI/T3/Elementos-de-lenguaje/ej3.js'
        - "Actividad 04": 'LMI/T3/Elementos-de-lenguaje/ej4.js'
        - "Actividad 05": 'LMI/T3/Elementos-de-lenguaje/ej5.js'
      - "Funciones":
        - "Actividad 01": 'LMI/T3/Funciones/ej1.js'
        - "Actividad 02": 'LMI/T3/Funciones/ej2.js'
      - "Programacion estructurada":
        - "Actividad 01": 'LMI/T3/Programacion-estructurada/ej1.js'
        - "Actividad 02": 'LMI/T3/Programacion-estructurada/ej2.js'
        - "Actividad 03": 'LMI/T3/Programacion-estructurada/ej3.js'
        - "Actividad 04": 'LMI/T3/Programacion-estructurada/ej4.js'
        - "Actividad 05": 'LMI/T3/Programacion-estructurada/ej5.js'

        
